### ISSUE TITLE
Basic Points For Badges - Custom Field

### ISSUE THREAD

**Issue by reneefromhold** [CareEvolution/MyDataHelpsUI#324]
The [Basic Points For Badges component](https://ui.mydatahelps.org/?path=/docs/container-basicpointsforbadges--docs) can be configured against a custom field. 

The component is configured to grant a badge once a value of XX in points is earned. Activities are then configured for earning points. For example, earn 50 points for every 8 hours of sleep or 20 points for completing a survey. 

In the case of the Custom activity, the total points earned for this activity will be 
custom field * activity points and does not consider if points were already granted for any given day. The result of not limiting the earning of points to a day or other time frame is that new points are earned each time the component is initialized. If a ppt views the component multiple times a day then they will earn additional points (custom field * activity points) each instance. 

Should there be a restriction on how often points are earned against a custom field?

**Comment by chrisnowak** [comment]
@reneefromhold I think that is just a bug - sorry.  I added the custom activity late.  The points awarded state should just be the value of the custom field * points, not adding that to the points on every render.  e.g. if someone has 5 in the custom field, and the points are 100 , it should always just be 500 points, not x + 500

**Comment by reneefromhold** [comment]
@chrisnowak Does this need to be recalculated on each ppt view? Or once per day? 
I'm envisioning an incentive where a gift card or device is offered. 
Could recalculating each time the ppt views vs once per day block the ability to do that easily?

**Comment by chrisnowak** [comment]
@reneefromhold each activity awards points differently and tracks it's state differently.  For daily data goals, it is mostly state to ensure we do not have to recalculate their goals based on their wearable data every day - that would be very bad perf-wise - so it tracks what days have been awarded.  Other goals are simpler and we do not have the same constraints, or might want to track state differently for other reasons like using a date anchor to know when we should query more data etc..

The custom activity one should just be a static "bonus" of points that is awarded basically.  It is for the case where you have an API or something that is writing the point total into the custom field outside of the basic goals that can be set up to be calculated by the front end.  So there is no need to track any additional state, if it is 3000 then the points awarded for that activity state is 3000, if it then changes to 300 then pointsAwarded would go to 300 (not 3300)

We can check/recalculate this on every view because it is just looking at a custom field so it is cheap (free, I believe)

**Comment by chrisnowak** [comment]
Oh well to clarify, the custom activity does allow for a multiplier, so if the custom field is 30 and the multiplier is 100 then it would be 3000 pointsawarded.  But if the CF drops to 3 then the pointsawarded would be 300.  Your fix in https://github.com/CareEvolution/MyDataHelpsUI/pull/325 is correct
